"""
FiBand - MySQL persistence. Connection configured via `.env` (see config.py).

Tables:
  measurements   -> on-demand measurements (heart rate, SpO2, blood pressure, stress) with timestamp
  hr_samples     -> historical heart-rate curve (1 point / 5 min), unique ts
  step_samples   -> historical steps/calories/distance (1 point / 15 min), unique ts
  stress_samples -> historical stress curve (1 point / 30 min), unique ts
  hrv_samples    -> historical HRV curve (ms, 1 point / 30 min), unique ts
"""
from __future__ import annotations

from datetime import datetime, timezone

import pymysql

from config import DB_CONFIG

SCHEMA = [
    """CREATE TABLE IF NOT EXISTS measurements (
        id      BIGINT AUTO_INCREMENT PRIMARY KEY,
        ts      DATETIME NOT NULL,
        metric  VARCHAR(32) NOT NULL,
        value   DOUBLE,
        value2  DOUBLE,
        unit    VARCHAR(16),
        source  VARCHAR(32) DEFAULT 'H59',
        INDEX (metric), INDEX (ts)
    ) CHARACTER SET utf8mb4""",
    """CREATE TABLE IF NOT EXISTS hr_samples (
        ts   DATETIME NOT NULL PRIMARY KEY,
        bpm  SMALLINT NOT NULL
    ) CHARACTER SET utf8mb4""",
    """CREATE TABLE IF NOT EXISTS step_samples (
        ts        DATETIME NOT NULL PRIMARY KEY,
        steps     INT NOT NULL,
        calories  INT,
        distance  INT
    ) CHARACTER SET utf8mb4""",
    """CREATE TABLE IF NOT EXISTS stress_samples (
        ts     DATETIME NOT NULL PRIMARY KEY,
        score  SMALLINT NOT NULL
    ) CHARACTER SET utf8mb4""",
    """CREATE TABLE IF NOT EXISTS hrv_samples (
        ts   DATETIME NOT NULL PRIMARY KEY,
        ms   SMALLINT NOT NULL
    ) CHARACTER SET utf8mb4""",
    """CREATE TABLE IF NOT EXISTS spo2_samples (
        ts    DATETIME NOT NULL PRIMARY KEY,
        spo2  SMALLINT NOT NULL
    ) CHARACTER SET utf8mb4""",
    """CREATE TABLE IF NOT EXISTS sleep_segments (
        sleep_date  DATE NOT NULL,
        idx         SMALLINT NOT NULL,
        stage       VARCHAR(8) NOT NULL,
        minutes     SMALLINT NOT NULL,
        PRIMARY KEY (sleep_date, idx)
    ) CHARACTER SET utf8mb4""",
    """CREATE TABLE IF NOT EXISTS sleep_sessions (
        sleep_date  DATE NOT NULL PRIMARY KEY,
        start_ts    DATETIME NOT NULL
    ) CHARACTER SET utf8mb4""",
    # User's personal notes for a single day (e.g. "10km run in the afternoon",
    # "vacation at the beach"): qualitative context passed to the AI analysis. One per local day.
    """CREATE TABLE IF NOT EXISTS day_notes (
        note_date   DATE NOT NULL PRIMARY KEY,
        note        TEXT,
        updated_at  DATETIME NOT NULL
    ) CHARACTER SET utf8mb4""",
    # AI analysis reports (generated by index.php via OpenRouter):
    # report_short = quick analysis, report = full analysis, report_diet = dietary advice
    """CREATE TABLE IF NOT EXISTS ai_report (
        id            BIGINT AUTO_INCREMENT PRIMARY KEY,
        ts            DATETIME NOT NULL,
        model         VARCHAR(64),
        days          INT,
        prompt        MEDIUMTEXT,
        report_short  MEDIUMTEXT,
        report        MEDIUMTEXT,
        report_diet   MEDIUMTEXT,
        tokens_in     INT,
        tokens_out    INT,
        INDEX (ts)
    ) CHARACTER SET utf8mb4""",
]


def ensure_database() -> None:
    """Creates the `fiband` database if it doesn't exist."""
    cfg = dict(DB_CONFIG)
    db = cfg.pop("database")
    conn = pymysql.connect(**cfg)
    with conn.cursor() as cur:
        cur.execute(f"CREATE DATABASE IF NOT EXISTS {db} CHARACTER SET utf8mb4")
    conn.commit()
    conn.close()


class Store:
    def __init__(self):
        ensure_database()
        self.conn = pymysql.connect(**DB_CONFIG, autocommit=True)
        with self.conn.cursor() as cur:
            for ddl in SCHEMA:
                cur.execute(ddl)

    def _fmt(self, ts: datetime) -> str:
        return ts.astimezone(timezone.utc).strftime("%Y-%m-%d %H:%M:%S")

    def last_sample_ts(self) -> datetime | None:
        """Timestamp (UTC) of the most recent history sample in the DB, or None if empty.
        Used for incremental sync: resumes from here instead of always downloading a
        fixed N days. Looks at the periodic-sample tables (not measurements,
        which are on-demand measurements only)."""
        tables = ("hr_samples", "step_samples", "stress_samples", "hrv_samples", "spo2_samples")
        union = " UNION ALL ".join(f"SELECT MAX(ts) AS m FROM {t}" for t in tables)
        with self.conn.cursor() as cur:
            cur.execute(f"SELECT MAX(m) FROM ({union}) x")
            row = cur.fetchone()
        if not row or row[0] is None:
            return None
        return row[0].replace(tzinfo=timezone.utc)   # saved in UTC (naive from pymysql)

    def add_measurement(self, metric: str, value: float | None, value2: float | None = None,
                        unit: str | None = None, ts: datetime | None = None) -> None:
        ts = ts or datetime.now(timezone.utc)
        with self.conn.cursor() as cur:
            cur.execute(
                "INSERT INTO measurements (ts, metric, value, value2, unit) VALUES (%s,%s,%s,%s,%s)",
                (self._fmt(ts), metric, value, value2, unit),
            )

    def upsert_hr(self, samples: list[tuple[datetime, int]]) -> int:
        if not samples:
            return 0
        with self.conn.cursor() as cur:
            cur.executemany(
                "INSERT INTO hr_samples (ts, bpm) VALUES (%s,%s) "
                "ON DUPLICATE KEY UPDATE bpm=VALUES(bpm)",
                [(self._fmt(t), int(hr)) for t, hr in samples],
            )
        return len(samples)

    def upsert_steps(self, samples: list[tuple[datetime, int, int, int]]) -> int:
        if not samples:
            return 0
        with self.conn.cursor() as cur:
            cur.executemany(
                "INSERT INTO step_samples (ts, steps, calories, distance) VALUES (%s,%s,%s,%s) "
                "ON DUPLICATE KEY UPDATE steps=VALUES(steps), calories=VALUES(calories), distance=VALUES(distance)",
                [(self._fmt(t), int(s), int(c), int(d)) for t, s, c, d in samples],
            )
        return len(samples)

    def _upsert_slot(self, table: str, col: str, samples: list[tuple[datetime, int]]) -> int:
        if not samples:
            return 0
        with self.conn.cursor() as cur:
            cur.executemany(
                f"INSERT INTO {table} (ts, {col}) VALUES (%s,%s) "
                f"ON DUPLICATE KEY UPDATE {col}=VALUES({col})",
                [(self._fmt(t), int(v)) for t, v in samples],
            )
        return len(samples)

    def upsert_stress(self, samples: list[tuple[datetime, int]]) -> int:
        return self._upsert_slot("stress_samples", "score", samples)

    def upsert_hrv(self, samples: list[tuple[datetime, int]]) -> int:
        return self._upsert_slot("hrv_samples", "ms", samples)

    def upsert_spo2(self, samples: list[tuple[datetime, int]]) -> int:
        return self._upsert_slot("spo2_samples", "spo2", samples)

    def replace_sleep(self, sleep_date: str, segments: list[tuple[str, int]],
                      start_ts: datetime | None = None) -> int:
        """Replaces the sleep stages for a day (YYYY-MM-DD): a list of (stage, minutes).
        start_ts = sleep start instant (to position the time axis)."""
        with self.conn.cursor() as cur:
            cur.execute("DELETE FROM sleep_segments WHERE sleep_date=%s", (sleep_date,))
            cur.execute("DELETE FROM sleep_sessions WHERE sleep_date=%s", (sleep_date,))
            if segments:
                cur.executemany(
                    "INSERT INTO sleep_segments (sleep_date, idx, stage, minutes) VALUES (%s,%s,%s,%s)",
                    [(sleep_date, i, st, int(m)) for i, (st, m) in enumerate(segments)],
                )
            if start_ts is not None:
                cur.execute("INSERT INTO sleep_sessions (sleep_date, start_ts) VALUES (%s,%s)",
                            (sleep_date, self._fmt(start_ts)))
        return len(segments)

    def close(self) -> None:
        self.conn.close()
